name: Test CDCI 3

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
    
    - name: Build 
      run: "docker build ."
      working-directory: /Docker_app/
      
    - name: Push
      run: "docker image push"
      
